version: '3'

services:
  backend:
    restart: always
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=rxit.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./backend/:/usr/src/app/backend
    command: flask run --host=0.0.0.0
