version: '3'

services:
  backend:
    restart: always
    build: ./backend
    expose:
      - "8000"
    # volumes:
    
    command: /usr/local/bin/gunicorn -w 2 -b :8000 backend:app

    # depends_on:
    #   - postgres

  # nginx:
  #   restart: always
  #   build: ./nginx
  #   ports: "80:80"
  #   volumes:
  #     - /www/static
  #   volumes_from:
  #     - web
  #   depends_on:
  #     - web

  # data:
  #   image: postgres:10.5
  #   volumes:
  #     -/var/lib/postgresql
  #   command: "true"

  # postgres:
  #   restart: always
  #   build: ./postgresql
  #   volumes_from:
  #     - data
  #   expose:
  #     -"5432"