version: '3'
services:
  backend:
    restart: always
    build: ./backend
    ports: 
      - "5000:5000"
    # expose:
    #   - "8000"
    # command: /usr/local/bin/gunicorn -w 2 -b :8000 src:app
    # depends_on: 
    #   - postgres

  postgres:
    restart: always
    image: postgres:10.5
    build: ./postgresql
    # volumes:
    #   - /var/lib/postgresql
    command: "true"
    expose:
      - "5432"