/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 26-Jun-2018 8:23:44 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS participant_participantid_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS Dispenser CASCADE
;

DROP TABLE IF EXISTS "Dispenser profile" CASCADE
;

DROP TABLE IF EXISTS DispenserComm CASCADE
;

DROP TABLE IF EXISTS DispenserDescription CASCADE
;

DROP TABLE IF EXISTS DispenserReview CASCADE
;

DROP TABLE IF EXISTS DispenserStatistics CASCADE
;

DROP TABLE IF EXISTS DispenserXcription CASCADE
;

DROP TABLE IF EXISTS Participant CASCADE
;

DROP TABLE IF EXISTS Participants CASCADE
;

DROP TABLE IF EXISTS Prescriber CASCADE
;

DROP TABLE IF EXISTS "Provider profile" CASCADE
;

/* Create Tables */

CREATE TABLE Dispenser
(
	dispenserId integer NOT NULL,
	description DispenserDescription NULL,
	statistics DispenserStatistics NULL,
	transcription DispenserXcription NULL,
	review DispenserReview NULL,
	communication DispenserComm NULL
)
;

CREATE TABLE "Dispenser profile"
(
	dispenser_id integer NULL,
	id integer NOT NULL,
	updated date NULL,
	volume numeric NULL,
	profile_id integer NULL
)
;

CREATE TABLE DispenserComm
(
	reasonsDuration double NULL,
	illegibleDuration double NULL,
	incompleteDuration double NULL,
	qMedsDuration double NULL,
	changeDuration double NULL,
	renewDuration double NULL,
	cancelDuration double NULL,
	physicianDuration double NULL,
	cancelFreq double NULL,
	changeFreq double NULL,
	illegibleFreq double NULL,
	incompleteFreq double NULL,
	physicianFreq double NULL,
	qMedsFreq double NULL,
	reasonsFreq double NULL,
	renewFreq double NULL,
	cancelElapsed double NULL,
	changeElapsed double NULL,
	illegibleElapsed double NULL,
	incompleteElapsed double NULL,
	physicianElapsed double NULL,
	qMedsElapsed double NULL,
	reasonsElapsed double NULL,
	renewElapsed double NULL,
	cancelFax boolean NULL,
	changelFax boolean NULL,
	changeFax boolean NULL,
	illegibleFax boolean NULL,
	incompleteFax boolean NULL,
	physicianFax boolean NULL,
	qMedsFax boolean NULL,
	reasonsFax boolean NULL,
	renewFax boolean NULL,
	cancelPhone boolean NULL,
	changePhone boolean NULL,
	illegiblePhone boolean NULL,
	incompletePhone boolean NULL,
	physicianPhone boolean NULL,
	qMedsPhone boolean NULL,
	reasonsPhone boolean NULL,
	cancelDM boolean NULL,
	changeDM boolean NULL,
	illegibleDM boolean NULL,
	incompleteDM boolean NULL,
	physicianDM boolean NULL,
	qMedsDM boolean NULL,
	reasonsDM boolean NULL,
	renewDM boolean NULL,
	dispenserId varchar NULL,
	surveyId timestamp without time zone NOT NULL
)
;

CREATE TABLE DispenserDescription
(
	name char NULL,
	numPharmacists int NULL,
	numRegTech int NULL,
	pmSystem char NULL,
	dispenser varchar NULL
)
;

CREATE TABLE DispenserReview
(
	reviewNewPtDiscussPost double NULL,
	reviewNewPtDiscussPre double NULL,
	reviewNewRxDiscussPre double NULL,
	reviewNewRxDiscussPost double NULL,
	reviewRepeatRxDiscussPost double NULL,
	reviewRepeatRxDiscussPre double NULL,
	reviewNotes char NULL,
	dispenserId varchar NULL,
	surveyId timestamp without time zone NOT NULL
)
;

CREATE TABLE DispenserStatistics
(
	totalRxAM double NULL,
	totalRxPM double NULL,
	totalRxEvg double NULL,
	totalRxWkend double NULL,
	walkInPrtRxWkend double NULL,
	walkInPrtRxAM double NULL,
	walkInPrtRxPM double NULL,
	walkInPrtRxEvg double NULL,
	walkInHandRxAM double NULL,
	walkInHandRxPM double NULL,
	walkInHandRxEvg double NULL,
	walkInHandRxWkend double NULL,
	faxRxAM double NULL,
	faxRxPM double NULL,
	faxRxEvg double NULL,
	faxRxkend double NULL,
	rxitRxAM double NULL,
	rxitRxPM double NULL,
	rxitRxEvg double NULL,
	rxitRxWkend double NULL,
	phoneRefillRxAM double NULL,
	phoneRefillRxPM double NULL,
	phoneRefillRxEvg double NULL,
	phoneRefillRxWkend double NULL,
	newPtAM double NULL,
	newPtPM double NULL,
	newPtEvg double NULL,
	newWkend double NULL,
	avgDispenseTime double NULL,
	dispenserId varchar NULL,
	surveyId timestamp without time zone NOT NULL
)
;

CREATE TABLE DispenserXcription
(
	durationNewPt double NULL,
	durationExistingPt double NULL,
	RepeatRx double NULL,
	inputRole DispenserRole NULL,
	dispenserId varchar NULL
)
;

CREATE TABLE Participant
(
	participantId integer NOT NULL   DEFAULT NEXTVAL(('"participant_participantid_seq"'::text)::regclass),
	name char NULL,
	street char NULL,
	city char NULL,
	postalCode char NULL,
	province char NULL,
	phone char NULL,
	email char NULL,
	role char NULL,
	dispenserId varchar NULL
)
;

CREATE TABLE Participants
(
	id integer NOT NULL,
	name varchar(50) NULL,
	contact varchar(50) NULL,
	street varchar(50) NULL,
	city varchar(50) NULL,
	province varchar(50) NULL,
	phone varchar(50) NULL,
	email varchar(50) NULL,
	type integer NULL
)
;

CREATE TABLE Prescriber
(
	prescriberId int NULL,
	description PrescriberDescription NULL,
	statistics PrescriberStatistics NULL,
	delivery PrescriberDelivery NULL,
	admin PrescriberAdmin NULL,
	preparation PrescriberPrep NULL,
	prescribing PrescriberMeds NULL
)
;

CREATE TABLE "Provider profile"
(
	id integer NOT NULL,
	provider_id integer NULL,
	profile_id integer NULL,
	updated date NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE Dispenser ADD CONSTRAINT PK_Dispenser
	PRIMARY KEY (dispenserId)
;

CREATE INDEX "IXFK_Dispenser profile_Participants" ON "Dispenser profile" (id ASC)
;

ALTER TABLE DispenserComm ADD CONSTRAINT PK_DispenserComm
	PRIMARY KEY (surveyId)
;

ALTER TABLE DispenserReview ADD CONSTRAINT PK_DispenserReview
	PRIMARY KEY (surveyId)
;

ALTER TABLE DispenserStatistics ADD CONSTRAINT PK_DispenserStatistics
	PRIMARY KEY (surveyId)
;

ALTER TABLE Participant ADD CONSTRAINT PK_Participant
	PRIMARY KEY (participantId)
;

ALTER TABLE Participants ADD CONSTRAINT PK_Participants
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_Provider profile_Participants" ON "Provider profile" (id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "Dispenser profile" ADD CONSTRAINT "FK_Dispenser profile_Participants"
	FOREIGN KEY (id) REFERENCES Participants (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE DispenserComm ADD CONSTRAINT FK_DispenserComm_Dispenser
	FOREIGN KEY (dispenserId) REFERENCES Dispenser (dispenserId) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE DispenserDescription ADD CONSTRAINT FK_DispenserDescription_Dispenser
	FOREIGN KEY (dispenser) REFERENCES Dispenser (dispenserId) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE DispenserReview ADD CONSTRAINT FK_DispenserReview_Dispenser
	FOREIGN KEY (dispenserId) REFERENCES Dispenser (dispenserId) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE DispenserStatistics ADD CONSTRAINT FK_DispenserStatistics_Dispenser
	FOREIGN KEY (dispenserId) REFERENCES Dispenser (dispenserId) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE DispenserXcription ADD CONSTRAINT FK_DispenserXcription_Dispenser
	FOREIGN KEY (dispenserId) REFERENCES Dispenser (dispenserId) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE Participant ADD CONSTRAINT FK_Participant_Dispenser
	FOREIGN KEY (dispenserId) REFERENCES Dispenser (dispenserId) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Provider profile" ADD CONSTRAINT "FK_Provider profile_Participants"
	FOREIGN KEY (id) REFERENCES Participants (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE participant_participantid_seq INCREMENT 1 START 1
;
