/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 17-Jun-2018 9:51:59 AM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Dispenser profile" CASCADE
;

DROP TABLE IF EXISTS Participants CASCADE
;

DROP TABLE IF EXISTS "Provider profile" CASCADE
;

/* Create Tables */

CREATE TABLE "Dispenser profile"
(
	dispenser_id integer NULL,
	id integer NOT NULL,
	updated date NULL,
	volume numeric NULL,
	profile_id integer NULL
)
;

CREATE TABLE Participants
(
	id integer NOT NULL,
	name varchar(50) NULL,
	contact varchar(50) NULL,
	street varchar(50) NULL,
	city varchar(50) NULL,
	province varchar(50) NULL,
	phone varchar(50) NULL,
	email varchar(50) NULL,
	type integer NULL
)
;

CREATE TABLE "Provider profile"
(
	id integer NOT NULL,
	provider_id integer NULL,
	profile_id integer NULL,
	updated date NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

CREATE INDEX "IXFK_Dispenser profile_Participants" ON "Dispenser profile" (id ASC)
;

ALTER TABLE Participants ADD CONSTRAINT PK_Participants
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_Provider profile_Participants" ON "Provider profile" (id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "Dispenser profile" ADD CONSTRAINT "FK_Dispenser profile_Participants"
	FOREIGN KEY (id) REFERENCES Participants (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Provider profile" ADD CONSTRAINT "FK_Provider profile_Participants"
	FOREIGN KEY (id) REFERENCES Participants (id) ON DELETE No Action ON UPDATE No Action
;
