"""restore simple name

Revision ID: 33c84a955935
Revises: 59faf2b50a4d
Create Date: 2018-08-22 15:30:11.281357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c84a955935'
down_revision = '59faf2b50a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dispenser', 'dispenser_name', new_column_name='name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispenser', sa.Column('dispenser_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('dispenser', 'name')
    # ### end Alembic commands ###
