"""add statistics to Prescriber

Revision ID: 396587d6c201
Revises: 730317caaa28
Create Date: 2018-08-28 18:07:09.974952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396587d6c201'
down_revision = '730317caaa28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescriber_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_pt_daily', sa.Numeric(), nullable=True),
    sa.Column('total_pt_weekly', sa.Numeric(), nullable=True),
    sa.Column('std_pt_daily', sa.Numeric(), nullable=True),
    sa.Column('std_pt_weekly', sa.Numeric(), nullable=True),
    sa.Column('ext_pt_daily', sa.Numeric(), nullable=True),
    sa.Column('ext_pt_weekly', sa.Numeric(), nullable=True),
    sa.Column('prop_ongoing_daily', sa.Numeric(), nullable=True),
    sa.Column('prop_ongoing_weekly', sa.Numeric(), nullable=True),
    sa.Column('total_rx_daily', sa.Numeric(), nullable=True),
    sa.Column('total_rx_weekly', sa.Numeric(), nullable=True),
    sa.Column('new_rx_daily', sa.Numeric(), nullable=True),
    sa.Column('new_rx_weekly', sa.Numeric(), nullable=True),
    sa.Column('renew_rx_daily', sa.Numeric(), nullable=True),
    sa.Column('renew_rx_weekly', sa.Numeric(), nullable=True),
    sa.Column('auth_rx_daily', sa.Numeric(), nullable=True),
    sa.Column('auth_rx_weekly', sa.Numeric(), nullable=True),
    sa.Column('multi_rx_daily', sa.Numeric(), nullable=True),
    sa.Column('multi_rx_weekly', sa.Numeric(), nullable=True),
    sa.Column('clarify_rx_daily', sa.Numeric(), nullable=True),
    sa.Column('clarify_rx_weekly', sa.Numeric(), nullable=True),
    sa.Column('request_rx_daily', sa.Numeric(), nullable=True),
    sa.Column('request_rx_weekly', sa.Numeric(), nullable=True),
    sa.Column('other_rx_daily', sa.Numeric(), nullable=True),
    sa.Column('other_rx_weekly', sa.Numeric(), nullable=True),
    sa.Column('other_rx_note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('prescriber', sa.Column('statistics_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prescriber', 'prescriber_statistics', ['statistics_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prescriber', type_='foreignkey')
    op.drop_column('prescriber', 'statistics_id')
    op.drop_table('prescriber_statistics')
    # ### end Alembic commands ###
