"""added authorization level

Revision ID: 46cc2a7e0091
Revises: edcca823a5a9
Create Date: 2018-08-15 11:47:54.725457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46cc2a7e0091'
down_revision = 'edcca823a5a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('private_user', sa.Column('authorization_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('private_user', 'authorization_level')
    # ### end Alembic commands ###
