"""distinguish name

Revision ID: 59faf2b50a4d
Revises: ec0ef34205b5
Create Date: 2018-08-22 15:08:01.988458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59faf2b50a4d'
down_revision = 'ec0ef34205b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispenser', sa.Column('dispenser_name', sa.String(), nullable=True))
    op.drop_column('dispenser', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispenser', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('dispenser', 'dispenser_name')
    # ### end Alembic commands ###
