"""adding participant type

Revision ID: 6b6633aba82a
Revises: 33c84a955935
Create Date: 2018-08-22 16:05:38.142724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6633aba82a'
down_revision = '33c84a955935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('participant_type', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'participant_type')
    # ### end Alembic commands ###
