"""add particpant types

Revision ID: da04e4571901
Revises: 56f59e1327b2
Create Date: 2018-08-22 14:26:51.389460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da04e4571901'
down_revision = '56f59e1327b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('participant_num', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('participant_type', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'participant_type')
    op.drop_column('user', 'participant_num')
    # ### end Alembic commands ###
