"""simplify participant

Revision ID: ec0ef34205b5
Revises: da04e4571901
Create Date: 2018-08-22 14:29:43.826349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec0ef34205b5'
down_revision = 'da04e4571901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('participant_name', sa.String(length=128), nullable=True))
    op.drop_column('user', 'participant_type')
    op.drop_column('user', 'participant_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('participant_num', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('participant_type', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('user', 'participant_name')
    # ### end Alembic commands ###
